# Generated by Django 2.0 on 2020-10-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritille',
            new_name='Article',
        ),
    ]
